openapi: 3.0.0
info:
  description: OMWebService API Documentation
  version: "1.0.0-oas3"
  title: OMWebService API Documentation
  contact:
    email: foo@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/components/{componentId}':
    get:
      tags:
        - developers
      parameters:
        - in: path
          name: componentId
          required: true
          schema:
            type: string
          example: Modelica.Electrical.Analog.Basic.Inductor
      responses:
        '200':
          description: foo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Component'
components:
  schemas:
    Component:
      type: object
      properties:
        id:
          type: string
        svgPath:
          type: string
          format: url
        connectors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              placement:
                type: object
                properties:
                  visible:
                    type: boolean
                  bottomLeft:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                  topRight:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                  rotation:
                    type: number
        parameters:
          type: array
          items:
            type: object
            properties:
              displayLabel:
                type: string
              displayValue:
                type: string
      example:
        id: Modelica.Electrical.Analog.Basic.Inductor
        svgPath: ./assets/inductor.svg
        connectors:
          - id: Modelica.Electrical.Analog.Interfaces.PositivePin
            placement:
              bottomLeft:
                x: 100
                y: 100
              topRight:
                x: 200
                y: 200
              rotation: 90
          - id: Modelica.Electrical.Analog.Interfaces.NegativePin
            placement:
              bottomLeft:
                x: 100
                y: 100
              topRight:
                x: 200
                y: 200
              rotation: 90
        parameters:
          - id: Modelica.Units.SI.Inductance
            displayLabel: Inductance
            displayValue: 1
