openapi: 3.0.0
info:
  description: OMWebService API Documentation
  version: "1.0.0-oas3"
  title: OMWebService API Documentation
  contact:
    email: foo@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/components/{componentId}':
    get:
      tags:
        - developers
      parameters:
        - in: path
          name: componentId
          required: true
          schema:
            type: string
          example: Modelica.Electrical.Analog.Basic.Inductor
      responses:
        '200':
          description: Component with specified componentId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Component'
  '/components':
    get:
      tags:
        - developers
      responses:
        '200':
          description: List of all components
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Component'
components:
  schemas:
    Component:
      type: object
      properties:
        id:
          type: string
        displayLabel:
          type: string
        svgPath:
          type: string
          format: url
        size:
          type: object
          properties:
            width:
              type: number
            height:
              type: number
        connectors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              svgPath:
                type: string
                format: url
              placement:
                type: object
                properties:
                  bottomLeft:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                  rotation:
                    type: number
        parameters:
          type: array
          items:
            type: object
            properties:
              displayLabel:
                type: string
              displayValue:
                type: string
      example:
        id: Modelica.Electrical.Analog.Basic.Inductor
        displayLabel: Analog Inductor
        svgPath: https://hostname:port/assets/Modelica.Electrical.Analog.Basic.Inductor.svg
        size:
          width: 310
          height: 210
        connectors:
          - id: Modelica.Electrical.Analog.Interfaces.PositivePin
            svgPath: https://hostname:port/assets/Modelica.Electrical.Analog.Interfaces.PositivePin.svg
            placement:
              bottomLeft:
                x: 100
                y: 100
              rotation: 90
          - id: Modelica.Electrical.Analog.Interfaces.NegativePin
            svgPath: https://hostname:port/assets/Modelica.Electrical.Analog.Interfaces.NegativePin.svg
            placement:
              bottomLeft:
                x: 100
                y: 100
              rotation: 90
        parameters:
          - id: Modelica.Units.SI.Inductance
            displayLabel: Inductance
            displayValue: 1
